import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/theme/theme";
import Header from "@/components/header/Header";

const iranSans = localFont({
  src: "../public/fonts/IRANSansXV.woff2",
  variable: "--font-iran-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${iranSans.variable}`}>
        <ThemeProvider theme={theme}>
          <Header />
          <Box
            sx={{
              paddingX: { xs: "1rem", sm: "8rem" },
              marginTop: { xs: "2.4rem", sm: "4.8rem" },
            }}
          >
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
